<?php

use Illuminate\Database\Seeder;
use App\Page;

class PagesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Page::create([
            'title' => 'Our Store',
            'slug' => "our-store",
            'type' => 'standard',
            'content' => '&lt;h2&gt;&lt;img style="width:100%;" src="http://lrecom.local/img/pages/page_image_5d5faecef35ff.jpeg" alt="page_image_5d5faecef35ff.jpeg"&gt;&lt;br&gt;&lt;h2&gt;&lt;br&gt;&lt;/h2&gt;&lt;h2&gt;Lorem ipsum dolor sit amet, consectetur adipiscing elit.&lt;/h2&gt;&lt;p&gt;Sed facilisis risus vel odio volutpat pellentesque. Nam non fringilla metus. Etiam molestie urna eget est faucibus porttitor. Vivamus ut dapibus dolor, at faucibus lacus. Vivamus nec lectus ante. Sed libero nisi, feugiat hendrerit pretium posuere, tempor nec enim. Maecenas porta nec urna sed semper. Phasellus id porta nulla, vel suscipit quam. &lt;/p&gt;&lt;p&gt;Donec vulputate luctus congue. Maecenas ante turpis, faucibus in elementum at, tincidunt et velit. Phasellus ante erat, pulvinar vel nisl nec, placerat hendrerit ipsum. Suspendisse varius rutrum orci a pretium. Mauris eleifend fringilla leo ut fringilla. Nunc convallis tellus vel diam laoreet vulputate. Integer ut imperdiet urna. Sed pharetra nisl ante, nec hendrerit ipsum vestibulum at. Nunc augue lacus, eleifend in purus ac, lobortis dapibus ex. Aliquam cursus tempus erat, et eleifend est pulvinar vel. Fusce lacinia ac est at consectetur. &lt;/p&gt;&lt;h2&gt;Nulla nec metus ac magna tincidunt convallis.&lt;/h2&gt;&lt;p&gt; Maecenas blandit at lectus non convallis. In hac habitasse platea dictumst. Vivamus imperdiet velit at purus commodo, vel maximus tortor facilisis. Aliquam eget faucibus nulla, a lobortis metus. In hac habitasse platea dictumst. Donec at sagittis odio. Integer ut posuere sem. Vestibulum erat erat, interdum et orci eu, blandit pretium nulla. Proin pellentesque nisi eget dolor elementum, et fringilla nunc tristique. &lt;/p&gt;&lt;/h2&gt;',
        ]);
        Page::create([
            'title' => 'Order Terms',
            'slug' => "order-terms",
            'type' => 'terms',
            'content' => '&lt;h2&gt;Lorem ipsum dolor sit amet, consectetur adipiscing elit. &lt;/h2&gt;&lt;p&gt;Sed facilisis risus vel odio volutpat pellentesque. Nam non fringilla metus. Etiam molestie urna eget est faucibus porttitor. Vivamus ut dapibus dolor, at faucibus lacus. Vivamus nec lectus ante. Sed libero nisi, feugiat hendrerit pretium posuere, tempor nec enim. Maecenas porta nec urna sed semper. Phasellus id porta nulla, vel suscipit quam. Donec vulputate luctus congue. Maecenas ante turpis, faucibus in elementum at, tincidunt et velit.Phasellus ante erat, pulvinar vel nisl nec, placerat hendrerit ipsum. Suspendisse varius rutrum orci a pretium. Mauris eleifend fringilla leo ut fringilla. Nunc convallis tellus vel diam laoreet vulputate. Integer ut imperdiet urna. Sed pharetra nisl ante, nec hendrerit ipsum vestibulum at. Nunc augue lacus, eleifend in purus ac, lobortis dapibus ex. Aliquam cursus tempus erat, et eleifend est pulvinar vel. Fusce lacinia ac est at consectetur. Nulla nec metus ac magna tincidunt convallis. Maecenas blandit at lectus non convallis. In hac habitasse platea dictumst.&lt;/p&gt;  &lt;h2&gt; Vivamus imperdiet velit at purus commodo, vel maximus tortor facilisis. &lt;/h2&gt;  &lt;p&gt;Aliquam eget faucibus nulla, a lobortis metus. In hac habitasse platea dictumst.                          Donec at sagittis odio. Integer ut posuere sem. Vestibulum erat erat, interdum et orci eu, blandit pretium nulla. Proin pellentesque nisi eget dolor elementum, et fringilla nunc tristique. Curabitur lobortis interdum nunc, ut sagittis diam porta ut. Duis nec mattis nisl, ac interdum ipsum. Praesent molestie rutrum enim, facilisis tempus massa molestie quis. Suspendisse consequat ligula volutpat, fringilla lectus ut, vulputate lorem.Nulla sollicitudin ligula ipsum, nec elementum libero congue eu. Proin malesuada non nisl pharetra dapibus. Donec varius mauris fringilla nunc viverra, et semper enim viverra. Maecenas et odio porta, placerat arcu vel, scelerisque elit. Fusce eget pretium ipsum. Suspendisse potenti. &lt;/p&gt;  &lt;h2&gt;Fusce convallis iaculis euismod.&lt;/h2&gt;  &lt;p&gt; Duis feugiat sem mauris, nec tincidunt felis feugiat vel. Vestibulum vulputate tempor libero. Donec sodales eu ex ut luctus. Cras et consequat purus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec laoreet gravida mi nec semper. Integer dapibus blandit tellus, in accumsan ligula rutrum id. Vivamus at tristique nibh. Vivamus eget odio ipsum. Ut pellentesque mattis augue, sit amet finibus nisl cursus et. Suspendisse id enim vitae sem interdum dictum quis ut diam. Aenean sit amet sapien dapibus, convallis lacus nec, consequat neque. Sed consequat, justo at euismod aliquet, turpis turpis interdum nisi, et fringilla lectus tellus ut libero. Vestibulum vitae pellentesque dui, et varius nulla. Pellentesque accumsan est eget rhoncus sagittis. &lt;/p&gt;',
        ]);
        Page::create([
            'title' => 'Payement Methods',
            'slug' => "payment-methods",
            'type' => 'terms',
            'content' => '&lt;h2&gt; Nam non fringilla metus.&lt;/h2&gt;  &lt;p&gt; Etiam molestie urna eget est faucibus porttitor. Vivamus ut dapibus dolor, at faucibus lacus. Vivamus nec lectus ante. Sed libero nisi, feugiat hendrerit pretium posuere, tempor nec enim. Maecenas porta nec urna sed semper. &lt;/p&gt;  &lt;h4&gt; Maecenas ante turpis, faucibus in elementum at, tincidunt et velit.&lt;/h4&gt;&lt;ul&gt;&lt;li&gt; Mauris eleifend fringilla leo ut fringilla. &lt;/li&gt;&lt;li&gt;Nunc convallis tellus vel diam laoreet vulputate.&lt;/li&gt;&lt;li&gt; Integer ut imperdiet urna. Sed pharetra nisl ante, nec hendrerit ipsum vestibulum at. &lt;/li&gt;&lt;li&gt;Nunc augue lacus, eleifend in purus ac, lobortis dapibus ex. &lt;/li&gt;&lt;li&gt;Aliquam cursus tempus erat, et eleifend est pulvinar vel. &lt;/li&gt;&lt;li&gt;Fusce lacinia ac est at consectetur. &lt;/li&gt;&lt;li&gt;Nulla nec metus ac magna tincidunt convallis. &lt;/li&gt;&lt;/ul&gt;  &lt;h2&gt;Maecenas blandit at lectus non convallis.&lt;/h2&gt;  &lt;p&gt; In hac habitasse platea dictumst. Vivamus imperdiet velit at purus commodo, vel maximus tortor facilisis. Aliquam eget faucibus nulla, a lobortis metus. In hac habitasse platea dictumst. Donec at sagittis odio. Integer ut posuere sem. Vestibulum erat erat, interdum et orci eu, blandit pretium nulla. Proin pellentesque nisi eget dolor elementum, et fringilla nunc tristique. Curabitur lobortis interdum nunc, ut sagittis diam porta ut. Duis nec mattis nisl, ac interdum ipsum. Praesent molestie rutrum enim, facilisis tempus massa molestie quis. Suspendisse consequat ligula volutpat, fringilla lectus ut, vulputate lorem. Nulla sollicitudin ligula ipsum, nec elementum libero congue eu.&lt;/p&gt;',
        ]);
        Page::create([
            'title' => 'Delivery',
            'slug' => "delivery",
            'type' => 'terms',
            'content' => '&lt;h2&gt;Lorem ipsum dolor sit amet, consectetur adipiscing elit.&lt;/h2&gt;&lt;p&gt; Sed facilisis risus vel odio volutpat pellentesque. Nam non fringilla metus. Etiam molestie urna eget est faucibus porttitor. Vivamus ut dapibus dolor, at faucibus lacus. Vivamus nec lectus ante. Sed libero nisi, feugiat hendrerit pretium posuere, tempor nec enim. Maecenas porta nec urna sed semper.&lt;/p&gt;  &lt;h4&gt; Phasellus id porta nulla, vel suscipit quam. &lt;/h4&gt;  &lt;ul&gt;&lt;li&gt;Donec vulputate luctus congue.&lt;/li&gt;&lt;li&gt; Maecenas ante turpis, faucibus in elementum at, tincidunt et velit.&lt;/li&gt;&lt;li&gt;  Phasellus ante erat, pulvinar vel nisl nec, placerat hendrerit ipsum.&lt;/li&gt;&lt;li&gt; Suspendisse varius rutrum orci a pretium. &lt;/li&gt;&lt;li&gt;Mauris eleifend fringilla leo ut fringilla.&lt;/li&gt;&lt;li&gt; Nunc convallis tellus vel diam laoreet vulputate.&lt;/li&gt;&lt;li&gt; Integer ut imperdiet urna.&lt;/li&gt;&lt;li&gt; Sed pharetra nisl ante, nec hendrerit ipsum vestibulum at.&lt;/li&gt;&lt;li&gt; Nunc augue lacus, eleifend in purus ac, lobortis dapibus ex. &lt;/li&gt;&lt;/ul&gt;&lt;h4&gt;Aliquam cursus tempus erat, et eleifend est pulvinar vel. &lt;/h4&gt;&lt;p&gt;Fusce lacinia ac est at consectetur. Nulla nec metus ac magna tincidunt convallis. Maecenas blandit at lectus non convallis. In hac habitasse platea dictumst. Vivamus imperdiet velit at purus commodo, vel maximus tortor facilisis. Aliquam eget faucibus nulla, a lobortis metus. In hac habitasse platea dictumst.  Donec at sagittis odio. Integer ut posuere sem. Vestibulum erat erat, interdum et orci eu, blandit pretium nulla. Proin pellentesque nisi eget dolor elementum, et fringilla nunc tristique. Curabitur lobortis interdum nunc, ut sagittis diam porta ut. Duis nec mattis nisl, ac interdum ipsum. &lt;/p&gt;  &lt;h4&gt;Praesent molestie rutrum enim, facilisis tempus massa molestie quis. &lt;/h4&gt;  &lt;p&gt;Suspendisse consequat ligula volutpat, fringilla lectus ut, vulputate lorem.  Nulla sollicitudin ligula ipsum, nec elementum libero congue eu. Proin malesuada non nisl pharetra dapibus. Donec varius mauris fringilla nunc viverra, et semper enim viverra. Maecenas et odio porta, placerat arcu vel, scelerisque elit. Fusce eget pretium ipsum. Suspendisse potenti. Fusce convallis iaculis euismod. &lt;/p&gt;',
        ]);
        Page::create([
            'title' => 'Returns',
            'slug' => "returns",
            'type' => 'terms',
            'content' => '&lt;h2&gt;Lorem ipsum dolor sit amet, consectetur adipiscing elit. &lt;/h2&gt;&lt;p&gt;Sed facilisis risus vel odio volutpat pellentesque. Nam non fringilla metus. Etiam molestie urna eget est faucibus porttitor. Vivamus ut dapibus dolor, at faucibus lacus. Vivamus nec lectus ante. Sed libero nisi, feugiat hendrerit pretium posuere, tempor nec enim. Maecenas porta nec urna sed semper. Phasellus id porta nulla, vel suscipit quam. Donec vulputate luctus congue. Maecenas ante turpis, faucibus in elementum at, tincidunt et velit. Phasellus ante erat, pulvinar vel nisl nec, placerat hendrerit ipsum. Suspendisse varius rutrum orci a pretium. Mauris eleifend fringilla leo ut fringilla. &lt;/p&gt;  &lt;h2&gt;Nunc convallis tellus vel diam laoreet vulputate. Integer ut imperdiet urna. &lt;/h2&gt;&lt;p&gt;Sed pharetra nisl ante, nec hendrerit ipsum vestibulum at. Nunc augue lacus, eleifend in purus ac, lobortis dapibus ex. Aliquam cursus tempus erat, et eleifend est pulvinar vel. Fusce lacinia ac est at consectetur. Nulla nec metus ac magna tincidunt convallis. Maecenas blandit at lectus non convallis. In hac habitasse platea dictumst. Vivamus imperdiet velit at purus commodo, vel maximus tortor facilisis. Aliquam eget faucibus nulla, a lobortis metus. In hac habitasse platea dictumst. Donec at sagittis odio. Integer ut posuere sem. Vestibulum erat erat, interdum et orci eu, blandit pretium nulla.&lt;/p&gt;&lt;h2&gt; Proin pellentesque nisi eget dolor elementum, et fringilla nunc tristique. &lt;/h2&gt;  &lt;p&gt;Curabitur lobortis interdum nunc, ut sagittis diam porta ut. Duis nec mattis nisl, ac interdum ipsum. Praesent molestie rutrum enim, facilisis tempus massa molestie quis. Suspendisse consequat ligula volutpat, fringilla lectus ut, vulputate lorem.  Nulla sollicitudin ligula ipsum, nec elementum libero congue eu. Proin malesuada non nisl pharetra dapibus. Donec varius mauris fringilla nunc viverra, et semper enim viverra. Maecenas et odio porta, placerat arcu vel, scelerisque elit. Fusce eget pretium ipsum. Suspendisse potenti. Fusce convallis iaculis euismod. Duis feugiat sem mauris, nec tincidunt felis feugiat vel. Vestibulum vulputate tempor libero. Donec sodales eu ex ut luctus.&lt;/p&gt;  &lt;h2&gt; Cras et consequat purus. &lt;/h2&gt;  &lt;p&gt;Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec laoreet gravida mi nec semper.  Integer dapibus blandit tellus, in accumsan ligula rutrum id. Vivamus at tristique nibh. Vivamus eget odio ipsum. Ut pellentesque mattis augue, sit amet finibus nisl cursus et. Suspendisse id enim vitae sem interdum dictum quis ut diam. Aenean sit amet sapien dapibus, convallis lacus nec, consequat neque. Sed consequat, justo at euismod aliquet, turpis turpis interdum nisi, et fringilla lectus tellus ut libero. Vestibulum vitae pellentesque dui, et varius nulla. Pellentesque accumsan est eget rhoncus sagittis. &lt;/p&gt;',
        ]);
        Page::create([
            'title' => 'Privacy And Security',
            'slug' => "privacy-security",
            'type' => 'standard',
            'content' => '&lt;h2&gt;Lorem ipsum dolor sit amet, consectetur adipiscing elit.&lt;/h2&gt;&lt;p&gt; Sed facilisis risus vel odio volutpat pellentesque. Nam non fringilla metus. Etiam molestie urna eget est faucibus porttitor. Vivamus ut dapibus dolor, at faucibus lacus. Vivamus nec lectus ante. Sed libero nisi, feugiat hendrerit pretium posuere, tempor nec enim. Maecenas porta nec urna sed semper. Phasellus id porta nulla, vel suscipit quam. Donec vulputate luctus congue. Maecenas ante turpis, faucibus in elementum at, tincidunt et velit. Phasellus ante erat, pulvinar vel nisl nec, placerat hendrerit ipsum. Suspendisse varius rutrum orci a pretium. Mauris eleifend fringilla leo ut fringilla. Nunc convallis tellus vel diam laoreet vulputate. Integer ut imperdiet urna. Sed pharetra nisl ante, nec hendrerit ipsum vestibulum at. Nunc augue lacus, eleifend in purus ac, lobortis dapibus ex. &lt;/p&gt;  &lt;h2&gt;Aliquam cursus tempus erat, et eleifend est pulvinar vel. &lt;/h2&gt;  &lt;p&gt;Fusce lacinia ac est at consectetur. Nulla nec metus ac magna tincidunt convallis. Maecenas blandit at lectus non convallis. In hac habitasse platea dictumst. Vivamus imperdiet velit at purus commodo, vel maximus tortor facilisis. Aliquam eget faucibus nulla, a lobortis metus. In hac habitasse platea dictumst.Donec at sagittis odio. Integer ut posuere sem. Vestibulum erat erat, interdum et orci eu, blandit pretium nulla. Proin pellentesque nisi eget dolor elementum, et fringilla nunc tristique. Curabitur lobortis interdum nunc, ut sagittis diam porta ut. Duis nec mattis nisl, ac interdum ipsum. Praesent molestie rutrum enim, facilisis tempus massa molestie quis. Suspendisse consequat ligula volutpat, fringilla lectus ut, vulputate lorem.  Nulla sollicitudin ligula ipsum, nec elementum libero congue eu. Proin malesuada non nisl pharetra dapibus. Donec varius mauris fringilla nunc viverra, et semper enim viverra. Maecenas et odio porta, placerat arcu vel, scelerisque elit. Fusce eget pretium ipsum. &lt;/p&gt;  &lt;h2&gt;Suspendisse potenti. Fusce convallis iaculis euismod. &lt;/h2&gt;  &lt;p&gt;Duis feugiat sem mauris, nec tincidunt felis feugiat vel. Vestibulum vulputate tempor libero. Donec sodales eu ex ut luctus. Cras et consequat purus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec laoreet gravida mi nec semper.  Integer dapibus blandit tellus, in accumsan ligula rutrum id. Vivamus at tristique nibh. Vivamus eget odio ipsum. Ut pellentesque mattis augue, sit amet finibus nisl cursus et. Suspendisse id enim vitae sem interdum dictum quis ut diam. Aenean sit amet sapien dapibus, convallis lacus nec, consequat neque. Sed consequat, justo at euismod aliquet, turpis turpis interdum nisi, et fringilla lectus tellus ut libero. Vestibulum vitae pellentesque dui, et varius nulla. Pellentesque accumsan est eget rhoncus sagittis. &lt;/p&gt;',
        ]);
    }
}
